blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()


    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


# Create your views here.

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html',{'blogs': blogs} )

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content%}
<div class="container">
    <h1>Blogs</h1>

    <h2>I have written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

    {% for blog in blogs %}
        <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
        <h5>{{ blog.date|date:'M d Y'|upper }}</h5>
        <p>{{ blog.description|truncatechars:100 }}</p>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content%}
<br>
<br>
<div class="container">
    <h1>{{ blog.title }}</h1>

    <h2>{{ blog.date|date:'F jS Y'}}</h2>

    {{ blog.description|safe }}
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
        {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'portfolio/custome.css' %}">

    <link rel="icon" type="image/jpg" href="{% static 'portfolio/flower.jpg' %}">

    <title>Hello, world!</title>
  </head>
  <body>
        <ul class="nav justify-content-center">
                <li class="nav-item">
                  <a class="nav-link active" href="{% static 'portfolio/2.pdf' %}">Resume</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">About</a>
                </li>
                
              </ul>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content%}
    <h1 class="text-center">Welcome to my portfolio</h1>
    <br>

    {% load static %}
    
    <img  style="width:600px;" src="{% static 'portfolio/photo3.jpeg' %}" class="mx-auto d-block">
    <br>
    <br>
    <br>
    <br>
    
    <div class="row">
        {% for project in projects %}
        <div class=col-lg-4 col-md-6>
            <h2 >{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
            {% if project.url %}
                <br><a href="{{ project.url }}">Link</a>
            {% endif %}
            
        </div>
        {% endfor %}                    
</div>
{% endblock %}